# Numpy

In [1]:
# Numpy is open-source library of python and its use for the scientific calculations.

# Why Numpy better than List?
# (1). Homogeneous data type
# (2). Less Memory Consumption
# (3). Fast Execution

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
a = [1,45,78,90]
type(a)

list

In [5]:
b = np.array(a)
b

array([ 1, 45, 78, 90])

In [6]:
b.ndim

1

In [7]:
p = [[1,2,3],[4,5,6],[7,8,9]]
q = np.array(p)
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print("Total Shape:" , q.shape)  ## shape = rows, columns
print("Total Elements:" , q.size)  ## size = row*column
print("Total Dimension:" , q.ndim)  ## ndim = dimension 1-D(x), 2-D(x,y), 3D(x,y,z)

Total Shape: (3, 3)
Total Elements: 9
Total Dimension: 2


In [11]:
a = []
size = int(input("Enter total elements:"))
for i in range(size):
    val = int(input("Enter Number:"))
    a.append(val)
b = np.array(a)
b  

Enter total elements: 6
Enter Number: 45
Enter Number: 72
Enter Number: 38
Enter Number: 578
Enter Number: 23
Enter Number: 90


array([ 45,  72,  38, 578,  23,  90])

# Pre-Defined Functions in Numpy

In [12]:
# Matrix ---> rows , columns
# Matrix ---> n(r)=n(c) ---> Symmatric Matrix , n(r)!=n(c) ---> Assymmatric Matrix
# Diagonal Positional Elements = [(1,1)(2,2)(3,3)(4,4).....(n,n)]

In [13]:
# Zeroes() ---> It will create an array in which all the values will be 0.

In [15]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [16]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# (2). ones() ---> It will create an array  in which all values will be 1.

In [24]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# (3). eye() ---> It will create an array in which diagonal position elements are 1.

In [26]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# (4). diag() ---> It will create an array of diiferent components in diagonal position.

In [28]:
a = np.array([2,56,45,87,36,62])
b = np.diag(a)
b

array([[ 2,  0,  0,  0,  0,  0],
       [ 0, 56,  0,  0,  0,  0],
       [ 0,  0, 45,  0,  0,  0],
       [ 0,  0,  0, 87,  0,  0],
       [ 0,  0,  0,  0, 36,  0],
       [ 0,  0,  0,  0,  0, 62]])

In [29]:
# (5). Random ---->
# (a). Randint() ---> It will generate random numbers in a given range
# syntax: np.random.randint(min_number, max_number, total numbers)

# (b). Rand() ---> It will generate random numbers from 0 to 1.
# syntax: np.random.rand(total_numbers)

In [32]:
a = np.random.randint(1,10,3)
a

array([4, 2, 9], dtype=int32)

In [33]:
b = np.random.rand(5)
b

array([0.45320167, 0.49312125, 0.73302648, 0.68959441, 0.62595721])